Factory/Models/Machine.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Machine
  {
    public int MachineId { get; set; }
    [Required(ErrorMessage = "* Please enter a model for the machine.")]
    public string Model { get; set; }

    // Collection Navigation Property
    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineersController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View(engineer);
      }
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
                                          .Include(engineer => engineer.JoinEntities)
                                          .ThenInclude(join => join.Machine)
                                          .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View(engineer);
      }
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      List<Machine> machines = _db.Machines.ToList();
      // If there are no machines available, then set to true; otherwise, set to false.
      ViewBag.NoMachinesBool = (machines.Count == 0) ? true : false;
      ViewBag.MachineId = new SelectList(machines, "MachineId", "Model");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
      #nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
      #nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineer.EngineerId, MachineId = machineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntity = _db.EngineerMachines.FirstOrDefault(join => join.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntity);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntity.EngineerId });
    }
  }
}

Factory/Controllers/MachinesController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if (!ModelState.IsValid)
      {
        return View(machine);
      }
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
                                        .Include(machine => machine.JoinEntities)
                                        .ThenInclude(join => join.Engineer)
                                        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      if (!ModelState.IsValid)
      {
        return View(machine);
      }
      _db.Machines.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      List<Engineer> engineers = _db.Engineers.ToList();
      // If there are no engineers available, then set to true; otherwise, set to false.
      ViewBag.NoEngineersBool = (engineers.Count == 0) ? true : false;
      ViewBag.EngineerId = new SelectList(engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
      #nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
      #nullable disable
      if (joinEntity == null && engineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntity = _db.EngineerMachines.FirstOrDefault(join => join.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntity);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntity.MachineId });
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h5>Factory > Machines > @Model.Model > License</h5>
<hr/>

<h2>License an Engineer for this Machine: @Model.Model</h2>
<hr/>

@if (ViewBag.NoEngineersBool)
{
  <p>There are no Engineers available to license.</p>
  <p><b>NOTE: </b>You must first employ an Engineer before you can license one to a Machine.</p>
  <h4>@Html.ActionLink("Add an Engineer", "Create", "Engineers")</h4>
}
else
{
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select an Engineer")
    <br/>
    @Html.DropDownList("EngineerId")

    <br/>
    <br/>
    <input type="submit" value="License" class="btn btn-primary" />
  }
}

<br/>
<div class="links container">
  <h5>@Html.ActionLink("Back to Machine", "Details", new { id = Model.MachineId })</h5>
</div>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h5>Factory > Machines > Create</h5>
<hr/>

<h2>Machine's Information:</h2>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Model)
  <br/>
  @Html.TextBoxFor(model => model.Model)
  <br/>
  @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
  <br/>
  <br/>
  <input type="submit" value="Submit" class="btn btn-primary" />
}

<br/>

<div class="links container">
  <h5>@Html.ActionLink("Back to Machines", "Index")</h5>
</div>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h5>Factory > Machines > @Model.Model > Remove</h5>
<hr/>

<h2>Are you sure you want to delete this Machine's records?</h2>
<br/>
<div class="container">
  <h4>@Html.DisplayNameFor(model => model.Model): @Html.DisplayFor(model => model.Model)</h4>
  <br/>
  @using(Html.BeginForm())
  {
    <input type="submit" value="Delete" class="btn btn-danger" />
  }
</div>
<br/>
<div class="links container">
  <h5>@Html.ActionLink("Back to Engineer", "Details", new { id = Model.MachineId })</h5>
</div>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine
@using Factory.Models;

<h5>Factory > Machines > @Model.Model</h5>
<hr/>
<h2>Machine Details</h2>
<h3>@Html.DisplayNameFor(model => model.Model): @Html.DisplayFor(model => model.Model)</h3>
<h3>Machine Id: @Html.DisplayFor(model => model.MachineId)</h3>
<hr/>

<div class="row justify-content-around">
  <div class="col-3 stack">

    <div class="links container">
      <br/>
      <h5>@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId })</h5>
      <br/>
      <h5>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</h5>
      <h5>@Html.ActionLink("Remove Machine", "Delete", new { id = Model.MachineId })</h5>
    </div>

  </div>

  <div class="col-6 details list-display stack">

    <h2>Licensed Engineers:</h2>

    @if (Model.JoinEntities.Count == 0)
    {
      <p>@Model.Model is not currently licensed to any engineers.</p>
    }
    else
    {
      @foreach (EngineerMachine join in Model.JoinEntities)
      {
        @using (Html.BeginForm("DeleteJoin", "Machines"))
        {
          <h4>
            <li>
              <div class="row">
                <div class="col">
                  @Html.ActionLink(join.Engineer.Name, "Details", "Engineers", new { id = join.Engineer.EngineerId })
                </div>
                <div class="col-1">
                  @Html.Hidden("joinId", @join.EngineerMachineId)
                  <input type="submit" value="X" class="btn btn-sm btn-x btn-outline-danger"/>
                </div>
              </div>
            </li>
          </h4>
        }
      }
    }

  </div>
</div>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h5>Factory > Machines > @( Model.Model == null ? "!" : Model.Model) > Edit</h5>
<hr/>

<h2>Update Information:</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Model)
  <br/>
  @Html.EditorFor(model => model.Model)
  <br/>
  @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
  <br/>
  <br/>
  <input type="submit" value="Save" class="btn btn-success" />
}

<br/>
<div class="links">
  <h5>@Html.ActionLink("Back to Machine", "Details", new { id = Model.MachineId })</h5>
</div>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>

<h5>Factory > Machines</h5>
<hr/>
<br/>

<div class="row justify-content-around">
  <div class="col-3">

    <div class="links container">
      <h5>@Html.ActionLink("Add New Machine", "Create")</h5>
    </div>

  </div>
  <div class="col-5 list-display">

    <h2>Available Machines:</h2>

    @if (Model.Count == 0)
    {
      <p>There are currently no Machines in the system.</p>
    }
    else
    {
      @foreach (Machine machine in Model)
      {
        <h4><li>@Html.ActionLink(machine.Model, "Details", new { id = machine.MachineId })</li></h4>
      }
    }

  </div>
</div>